### ISSUE TITLE
ANN: Move of Rotations.jl to a community-maintained location

### ISSUE THREAD

**Issue by c42f** [JuliaGeometry/Rotations.jl#110]
Hi all, I am planning to move Rotations.jl to @JuliaGeometry because it has been community maintained for some time now and having it in a community-owned location will make some project admin tasks — such as adding new maintainers and github bots — easier.

To mention some people who have maintained or contributed here in the past and may be interested in the move: @tkoolen @andyferris @awbsmith @ryanelandt @jw3126 @rdeits @timholy. I hope this makes sense to everyone? I'm happy to add current maintainers in the new location, just let me know if you'd like that or have other concerns about the move.

I also plan to do the same for CoordinateTransformations.jl which has much the same group of contributors. (And PlyIO.jl, but I won't make a separate announcement about that because it's fairly obscure.)

I've already discussed the move with current @FugroRoames people @draffelt and @bertrand-caron and I'll be adding a small acknowledgement section to the READMEs - see https://github.com/FugroRoames/Rotations.jl/pull/109)

**Comment by tkoolen** [comment]
Yeah, that sounds great to me!

**Comment by rdeits** [comment]
Yup, sounds good!

**Comment by bertrand-caron** [comment]
@c42f Should we modify the README to have this repo point to the new one explicitly?

**Comment by andyferris** [comment]
@bertrand-caron Do you mean within the markdown content? (GitHub provides redirects (forever?) when you move or rename a repository).

**Comment by c42f** [comment]
@bertrand-caron what we should do here is to *move* the repository — this means that everything is preserved, including the issues and pull requests.  It also means than anyone going to https://github.com/FugroRoames/Rotations.jl will get redirected to JuliaGeometry/Rotations.jl, including operations on the git remote.

So I thought we'd merge the acknowledgements, including a link back to the FugroRoames organization. Then I believe we need someone who's got repo creation rights at JuliaGeometry and admin rights to FugroRoames/Rotations.jl to do the move and check everything is working. If you're ok to give me admin to these three repos individually I'm happy to do the rest of the job.

**Comment by timholy** [comment]
Unless I'm misreading, you should have adequate permissions at JuliaGeometry.

**Comment by andyferris** [comment]
Oh good - I think it’s the FugroRoames side we may be waiting on, Tim.

**Comment by c42f** [comment]
Yes, I'm an owner in JuliaGeometry so that's all good :-) I just need someone to give me admin permissions to the individual repos on this side and we can go ahead.

**Comment by ryanelandt** [comment]
Sorry for the late response. The proposed transition sounds good to me.

**Comment by c42f** [comment]
No worries at all; I should clarify to say I'm not expecting everyone who has ever contributed to chime in here. Just wondering if there's something I've overlooked.

@bertrand-caron I think everyone is pretty much in agreement about what to do here, so I'd like to go ahead with it soon — currently I'm blocked from making new maintainence releases at CoordinateTransformations and PlyIO because JuliaRegistrator isn't installed.

So if you can give me admin to these three repos I'll initiate the move. Let me know if that's not possible for some reason and we'll figure something else out.

**Comment by bertrand-caron** [comment]
Hi @c42f , sorry for the slow reponse. I don't have admin write on the FugroRoames account but I can laise with someone that does, hopefully today. Can you confirm the list of repo to be transfered to you?

**Comment by c42f** [comment]
Thanks! I'm thinking of:
* Rotations.jl
* CoordinateTransformations.jl
* PlyIO.jl

**Comment by bertrand-caron** [comment]
@c42f Sorry, this might take another day or two, I'll be in touch :)

**Comment by bertrand-caron** [comment]
@c42f Should happen sometimes today :)

**Comment by c42f** [comment]
Ping! Would be great to get permissions so I can move these and make some maintenance releases (https://github.com/FugroRoames/CoordinateTransformations.jl/issues/53)

**Comment by bertrand-caron** [comment]
I've moved this, closing the issue now :)

**Comment by c42f** [comment]
Thanks very much! I've landed all three here in JuliaGeometry.
