### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by c42f** [JuliaGeometry/Rotations.jl#112]
What do we need to work toward version 1.0?

We could do this right away (this package has been quite stable for a long time), though it might be an opportunity to look at integrating some of the great stuff from DifferentialRotations.jl

@bjack205 what are your thoughts? Do you think you'd have time for such a project?

XRef: https://github.com/RoboticExplorationLab/DifferentialRotations.jl/issues/1#issuecomment-589885265

**Comment by c42f** [comment]
Some extra action points from #113:
* Delete the existing Quat code and rename UnitQuaternion to Quat (deprecation strategy: https://github.com/JuliaGeometry/Rotations.jl/pull/113#issuecomment-608957343)
* Rename RodriguesVec->RotationVec (ref. https://github.com/JuliaGeometry/Rotations.jl/pull/113#issuecomment-604114831)

@bjack205 did I miss anything?

**Comment by bjack205** [comment]
This would be great, those were the left-over to-dos from #113. I can tackle those. 

A few other questions
- Are we keeping `UnitQuaternion` or `Quat`? Per https://github.com/JuliaGeometry/Rotations.jl/pull/113#issuecomment-608957343 I thought the idea was to keep `UnitQuaternion`, but the comment above says the opposite? 
- Should we export any additional functions? Candidates include:
    - `lmult`, `rmult`, `tmat`, `hmat`
    - `params`: TBH I'm not the biggest fan of this function name. Any other better suggestions?
    -  `rotation_error` and `add_error`
    - `pure_quaternion`
    - `kinematics`

Lastly, more of a procedural question (I'm new to this :smiley: ): should I make these changes in a separate branch and then create a PR? Or just make commits directly to the master branch?

**Comment by andyferris** [comment]
> Lastly, more of a procedural question (I'm new to this smiley ): should I make these changes in a separate branch and then create a PR? Or just make commits directly to the master branch?

Generally work through PRs where possible. (The smaller the change hopefully the quicker it will get merged).

**Comment by c42f** [comment]
> Are we keeping UnitQuaternion or Quat

Sorry for the confusion, that's just me typo-ing! I somewhat favor `UnitQuaternion` for clarity. What do you think @andyferris?

> Should we export any additional functions

Good/hard question. Generally it's safe to be conservative and not export these. Ideally consider the question "could my exported function name mean anything else?" Very generic names are best paired with very generic meanings because `using` will bring them into the global namespace. If the meaning is abstract but well defined, it's possible for many packages to consistently overload the same function with new types.

I'd say `rotation_error` seems safe from this point of view, but `add_error` not so much. I would keep `lmult`, `rmult`, `tmat`, `hmat` internal for now (actually I'm not quite sure these convenience matrices are API we want in `Rotations` itself — are they generic rotation-related functionality or more application specific?)

`kinematics` seems pretty general though again: could it mean something else in a different context? If so, it's best to either make the name more specific, avoid exporting it, or generalize the meaning so it can be reused in other contexts.  (Generalizing the meaning usually leads to one of the `*Base.jl` or `*Core.jl` "interface packages" which allow various implementation packages to agree on a shared meaning for a function which everyone extends for their own types. Going in that direction may be premature for this package and part of the ecosystem though. It's most helpful when a few different but related packages need to expose the same API.)

`params` is a very generic name so shouldn't be exported. It may be clearer what to do with this if we figure out how to integrate the package with the `ChainRulesCore` API. Same comment for the many derivatives which you've written out.

> should I make these changes in a separate branch and then create a PR? Or just make commits directly to the master branch?

Thanks for asking. What Andy said; but to elaborate: I tend to use PRs for any nontrivial change on "serious" packages which I expect other people to be using. On my own repos I often use them to get a cross platform CI check even when nobody else is contributing. As I said in #113 

> Rough guidelines for contributors are common sense things: keep the tests passing, add tests to cover new functionality, small incremental changes are good when possible. For new API surface area (especially exports) it's always a good idea to be conservative and get opinions from other contributors where that's possible. I usually try to give it a couple of weeks for people to chime in on new APIs and bump a prospective PR once before merging.

I guess I implicitly assume a PR-based workflow there :-)

**Comment by bjack205** [comment]
I think we've finished the to-dos we listed for version 1.0. Is there anything else before we submit it to be registered?

**Comment by c42f** [comment]
Would be nice to clear up #114 I guess, but not exactly required.

**Comment by c42f** [comment]
@bjack205 if you want to do the release, it should be as simple as updating the Project.toml version to 1.0.0 (use a PR I guess). Once that's merged, commenting `@JuliaRegistrator register` here should trigger a release.

**Comment by c42f** [comment]
Haha, eek! And here I was, thinking that quoting JuliaRegistrator's name as code would prevent it from activating.  Luckily it's got safeguards against re-registering an existing version.

**Comment by bjack205** [comment]
@JuliaRegistrator register
Registering Rotations.jl v1.0

**Comment by c42f** [comment]
This is all sorted, thanks to the epic effort by Brian :-)
