### ISSUE TITLE
Register v1.0.1

### ISSUE THREAD

**Issue by bjack205** [JuliaGeometry/Rotations.jl#123]
@JuliaRegistrator register
New patch version with some minor tweaks

**Comment by c42f** [comment]
Oh good, you've already triggered the registration.

I accidentally tried to re-register it myself - https://github.com/JuliaGeometry/Rotations.jl/commit/8b4008492386f9972603c20c8f079dc5520d8480. As you can see, you can just comment on the commit without opening an issue, if you like (I find this works well for non-breaking releases when there's no real need to coordinate the release).

**Comment by bjack205** [comment]
Oh, nice. Good trick to know :+1:
