### ISSUE TITLE
RotationVec(angle, 0.0, 0.0) does not return a Rotation Matrix for angle > 1e15

### ISSUE THREAD

**Issue by traversaro** [JuliaGeometry/Rotations.jl#137]
I am on Windows, with this Julia&Rotations versions: 
~~~julia
julia> VERSION
v"1.5.3"

julia> Pkg.status()
Status `C:\Users\STraversaro\.julia\environments\v1.5\Project.toml`
  [91a5bcdd] Plots v1.10.1
  [6038ab10] Rotations v1.0.2
  [37e2e46d] LinearAlgebra
~~~

If I try to pass to `RotationVec` a value higher then 1e15, it does not return anymore a Rotation matrix, see: 
~~~julia
julia> RotationVec(1e7, 0.0, 0.0)
3×3 RotationVec{Float64} with indices SOneTo(3)×SOneTo(3)(1.0e7, 0.0, 0.0):
 1.0   0.0        0.0
 0.0  -0.90727   -0.420548
 0.0   0.420548  -0.90727

julia> RotationVec(1e19, 0.0, 0.0)
3×3 RotationVec{Float64} with indices SOneTo(3)×SOneTo(3)(1.0e19, 0.0, 0.0):
 0.312547  0.0       0.0
 0.0       0.312547  0.0
 0.0       0.0       0.312547
~~~

Interestingly, passing similar values to `AngleAxis` seems to be working fine:
~~~julia
julia> AngleAxis(1e7, 1.0, 0.0, 0.0)
3×3 AngleAxis{Float64} with indices SOneTo(3)×SOneTo(3)(1.0e7, 1.0, 0.0, 0.0):
 1.0   0.0        0.0
 0.0  -0.90727   -0.420548
 0.0   0.420548  -0.90727

julia> AngleAxis(1e19, 1.0, 0.0, 0.0)
3×3 AngleAxis{Float64} with indices SOneTo(3)×SOneTo(3)(1.0e19, 1.0, 0.0, 0.0):
 1.0   0.0        0.0
 0.0  -0.374905   0.927063
 0.0  -0.927063  -0.374905
~~~

To understand more about this, I tried to plot the determinant of the matrix for various values of angle with this script:
~~~julia
using Rotations
using LinearAlgebra

function myRotationVec(x,y,z)
    angle = norm([x y z]);
    if(angle > 0)
      axis = [x y z]/angle;
    else
      axis = [1.0 0.0 0.0];
    end
    return AngleAxis(angle, axis[1], axis[2], axis[3])
end

using Plots
angleRange = 10.0 .^(range(0, step=0.01,stop=150));
detRotVec = copy(angleRange);
for i=1:length(angleRange)
    detRotVec[i] = det(RotationVec(angleRange[i],0.0,0.0))
end


detMyRotVec = copy(angleRange);
for i=1:length(angleRange)
    detMyRotVec[i] = det(myRotationVec(angleRange[i],0.0,0.0))
end

plot(angleRange, detRotVec, xaxis=:log)

plot(angleRange, detMyRotVec, ylims=(0,2), xaxis=:log)
~~~

And from this I see that the determinant seems to be different from 1.0 around ~1e15 : 
![det_rotvector](https://user-images.githubusercontent.com/1857049/104132226-1814d280-537c-11eb-8868-ff47667b8cf7.png)

While the naive `myRotationVec` that uses `AngleAxis`  seems to always return a Rotation matrix:
![det_myrotvector](https://user-images.githubusercontent.com/1857049/104132243-3975be80-537c-11eb-980b-fa985ef2c0ca.png)

**Comment by traversaro** [comment]
I would be happy to checkout what is going on myself, and as I am rather beginner Julia user, any pointer on relevant part of code to checkout are highly appreciated.

**Comment by c42f** [comment]
> I would be happy to checkout what is going on mysel

That would be great!

`@which` can be helpful in tracking down the method being called.  Though in this case it's a little tricky. I followed the trail to the `UnitQuaternion` conversion — it seems that's failing for large angles.  The code is here https://github.com/JuliaGeometry/Rotations.jl/blob/2d6bba95317d74c82dc73c9fe68fb199f00e7738/src/angleaxis_types.jl#L161

**Comment by traversaro** [comment]
Thanks for the hint @c42f ! I tried to propose a fix in https://github.com/JuliaGeometry/Rotations.jl/pull/142 .
