### ISSUE TITLE
`zero(UnitQuaternion)` doesn't make sense (for me)

### ISSUE THREAD

**Issue by hyrodium** [JuliaGeometry/Rotations.jl#157]
Here's an example script:
```julia
julia> using Rotations

julia> zero(UnitQuaternion)
3×3 UnitQuaternion{Float64} with indices SOneTo(3)×SOneTo(3)(1.0, 0.0, 0.0, 0.0):
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> zero(UnitQuaternion) + zero(UnitQuaternion)
3×3 StaticArrays.SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
 2.0  0.0  0.0
 0.0  2.0  0.0
 0.0  0.0  2.0

julia> zero(UnitQuaternion) + zero(UnitQuaternion) == zero(UnitQuaternion)
false

julia> zero(UnitQuaternion) == one(UnitQuaternion)
true
```
And we don't have tests for `zero(UnitQuaternion)`, so maybe we can just drop the definition.
https://github.com/JuliaGeometry/Rotations.jl/blob/v1.0.2/src/unitquaternion.jl#L204

**Comment by goretkin** [comment]
I think we cannot have it both ways that

1. Rotations are `<:AbstractMatrix`:
https://github.com/JuliaGeometry/Rotations.jl/blob/38b208b3f69495a1dcab744e6972b320d56e2455/src/core_types.jl#L7

2. Rotations don't have inappropriate semantics defined on them, like `zero` and `+`. 

Unfortunately, there isn't a formal notion of interfaces in Julia (yet), and I wonder if there is another example of something that is an `AbstractMatrix`, but does not have additive structure.

**Comment by andyferris** [comment]
We shouldn’t have a `zero(UnitQuaternion)` defined at all. 

The rotations are of the Lie group not the Lie algebra. There is a multiplicative identity only. The relevant field is `SMatrix{3, 3}` which is what `zero` should return.

**Comment by goretkin** [comment]
> We shouldn’t have a `zero(UnitQuaternion)` defined at all.

I agree.

My comment was with regards to the error definitions added here: https://github.com/JuliaGeometry/Rotations.jl/pull/159/files#r635647448 . This wasn't clear from my comment, so clarifying it now.

**Comment by hyrodium** [comment]
>I wonder if there is another example of something that is an AbstractMatrix, but does not have additive structure.

For example, `Real` is a abstract type for [real number](https://en.wikipedia.org/wiki/Real_number), but the `Int64` type doesn't have "appropriate" division `/` function, because the [set of integer](https://en.wikipedia.org/wiki/Integer) is [ring](https://en.wikipedia.org/wiki/Ring_(mathematics)), but not [field](https://en.wikipedia.org/wiki/Field_(mathematics)).
By analogy with this, I think there's no problem with `Rotation <: AbstractMatrix` even if we don't have "appropriate" `zero` and `+` for `Rotation`.

**Comment by goretkin** [comment]
e.g. `1 / 2` is defined, it's just not closed over `Int`.

I think it would be unexpected for something to be a  `<:Number` but not have `/` defined at all.

**Comment by hyrodium** [comment]
Sorry for misleading example. I've updated the PR.
https://github.com/JuliaGeometry/Rotations.jl/pull/159#issuecomment-845097250
