### ISSUE TITLE
Extract Euler angles from rotation matrix

### ISSUE THREAD

**Issue by JinraeKim** [JuliaGeometry/Rotations.jl#158]
It seems that there is no method for extraction of Euler angles from rotation matrix.

For example,
`angles(x::RotXYZ)` provides `[theta1, theta2, theta3]`.

**Comment by hyrodium** [comment]
We have a `Rotations.params` function for `UnitQuaternion`, `MRP` and `RodriguesParam` to get the underlying parameters.
I think it's better to add the following methods:

* `Rotations.params(::RotX)` and other 1-axis rotations.
* `Rotations.params(::RotXY)` and other 2-axis rotations.
* `Rotations.params(::RotXYZ)` and other 3-axis rotations.
* `Rotations.params(::AngleAxis)` 
* `Rotations.params(::RotationVec)` 
* `Rotations.params(::Angle2d)` 

I'm not sure whether we should add `Rotations.params(::RotMatrix)`.
