### ISSUE TITLE
Define `conj(r::Rotation) = r` ?

### ISSUE THREAD

**Issue by hyrodium** [JuliaGeometry/Rotations.jl#182]
## The problem
The operator for matrix `transpose ∘ adjoint` should be equal to `conj`.
But, the following code produce `SMatrix`.

```julia
julia> r = MRP(1.0, 2.0, 3.0)
3×3 MRP{Float64} with indices SOneTo(3)×SOneTo(3)(1.0, 2.0, 3.0):
  0.537778   0.764444   -0.355556
 -0.622222   0.644444    0.444444
  0.568889  -0.0177778   0.822222

julia> r'  # same as adjoint(r)
3×3 MRP{Float64} with indices SOneTo(3)×SOneTo(3)(-1.0, -2.0, -3.0):
  0.537778  -0.622222   0.568889
  0.764444   0.644444  -0.0177778
 -0.355556   0.444444   0.822222

julia> transpose(r)
3×3 MRP{Float64} with indices SOneTo(3)×SOneTo(3)(-1.0, -2.0, -3.0):
  0.537778  -0.622222   0.568889
  0.764444   0.644444  -0.0177778
 -0.355556   0.444444   0.822222

julia> (transpose∘adjoint)(r)
3×3 MRP{Float64} with indices SOneTo(3)×SOneTo(3)(1.0, 2.0, 3.0):
  0.537778   0.764444   -0.355556
 -0.622222   0.644444    0.444444
  0.568889  -0.0177778   0.822222

julia> conj(r)
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
  0.537778   0.764444   -0.355556
 -0.622222   0.644444    0.444444
  0.568889  -0.0177778   0.822222
```

## How to solve it

At first, I thought it's okay to just define `conj(r::Rotation) = r`. However, some scripts in this package thinking a rotation as a unitary matrix. (e.g. https://github.com/JuliaGeometry/Rotations.jl/blob/master/src/core_types.jl#L213)

Is it expected to handle complex matrices in this package? (I guess not)

**Comment by andyferris** [comment]
It’s ok to assume these matrices are orthogonal, not just unitary.

I’d go as far as “special” orthogonal - determinant of 1 - since we have conversions from `RotMatrix` that only work in the “special” case.

(That comment is very old).

Also from distant memory I thought previously `conj(a::AbstractArray{<:Real}) = a` was defined by Julia - is that not there anymore?

**Comment by hyrodium** [comment]
>Also from distant memory I thought previously `conj(a::AbstractArray{<:Real}) = a` was defined by Julia - is that not there anymore?

There still be, but `StaticArrays` package overload the `conj`:
```julia
@inline conj(a::StaticArray) = map(conj, a)
```
This should be fixed in StaticArrays.jl, but we can just add `conj` method for `Rotation` for now.

**Comment by andyferris** [comment]
Either way, I can quickly merge something into StaticArrays if that's better.

**Comment by hyrodium** [comment]
I've opened a PR for this.
https://github.com/JuliaArrays/StaticArrays.jl/pull/969

(At first, I had added `@inline conj(a::StaticArray{<:Tuple,<:Real}) = a` to StaticArrays, but I realized we may drop the original `conj` definition.)

**Comment by hyrodium** [comment]
This will be fixed in StaticArrays, so I'll close this issue.
