### ISSUE TITLE
Allow support for Quaternions.jl v0.7+?

### ISSUE THREAD

**Issue by Dsantra92** [JuliaGeometry/Rotations.jl#246]
Is there any function or requirement that is preventing support for v0.7 of Quaternions.jl? I am entirely new to this ecosystem, so pardon me if this question comes out as naive 🐱 .

**Comment by hyrodium** [comment]
Thanks for the ping! #245 will update the version of Quaternions.jl, and #243 is a PR to avoid the breaking changes introduced in Quaternions.jl v0.7.0. The main problem in #243 is around automatic differentiation with dual numbers. I will try fixing it in a few days.
